## 测试大文件上传

### 1. 创建大文件

`dd if=/dev/zero of=2G bs=1G count=2`

`dd if=/dev/zero of=80M bs=80M count=1`

`dd if=/dev/zero of=100M bs=100M count=1`

`ll -lh` 显示文件换算后的大小

500MB文件大小：524288000

### 2. 按照lakefs操作手册，上传大文件

1. 通过界面创建新的bucket （服务器错误导致之前的bucket出了问题）
2. 修改 tier/das3.go newV2改为newV4

### 3. log报错

1. 报错：internal error

   ![批注 2019-05-09 150408](C:\Users\Jarvis.LAPTOP-HV4II8QE\AppData\Roaming\Typora\typora-user-images\批注 2019-05-09 150408.png)

   > 大连s3接口出错

2. Put显示：无

   ![1557387147634](C:\Users\Jarvis.LAPTOP-HV4II8QE\AppData\Roaming\Typora\typora-user-images\1557387147634.png)

   > 大连调节s3接口解决
   
3. timeout![1557457573361](C:\Users\Jarvis.LAPTOP-HV4II8QE\AppData\Roaming\Typora\typora-user-images\1557457573361.png)

4. Put显示：got EOF

   ![1558059463284](C:\Users\Jarvis.LAPTOP-HV4II8QE\AppData\Roaming\Typora\typora-user-images\1558059463284.png)

   > 更换新的bucket

5. 更换新的bucket后；Put显示：Got EOF

   ![1558069228973](C:\Users\Jarvis.LAPTOP-HV4II8QE\AppData\Roaming\Typora\typora-user-images\1558069228973.png)

   > 大连s3接口出错

6. 大连解决问题后，上传中断，遇到内部错误，自动重传

   ![1558079211884](C:\Users\Jarvis.LAPTOP-HV4II8QE\AppData\Roaming\Typora\typora-user-images\1558079211884.png)

   > 疑似大连出错

7. 再次遇到内部错误（Put demo/1144ca3.20190520.024831.986 got We encountered an internal error. Please try again. ）

   ![1558336526832](C:\Users\Jarvis.LAPTOP-HV4II8QE\AppData\Roaming\Typora\typora-user-images\1558336526832.png)

8. 遇到内部错误，只能上传到268369920

   然后重传，传到67043328，停止上传，没有错误提示

   ![1558402538299](C:\Users\Jarvis.LAPTOP-HV4II8QE\AppData\Roaming\Typora\typora-user-images\1558402538299.png)





### Q ＆ Ａ

------

1. **创建大文件**

   执行命令后卡住，杀掉进程，执行命令

   `dd if=/dev/zero of=5G bs=5G count=1`

   返回如下信息

   `dd: memory exhausted by input buffer of size 5368709120 bytes (5.0 GiB)
   [1]+  Killed                  dd if=/dev/zero of=5G bs=1G count=5`

   > [命令参考 ](https://blog.csdn.net/beswkwangbo/article/details/46375795) [报错参考](http://blog.jues.org.cn/post/dd-memory-exhausted-by-input-buffer-of-size-1073741824-bytes-1.0-gib.html)
   >
   > bs（buffer size）大于 空闲内存（free mem）
   >
   > 修改命令为
   >
   > `dd if=/dev/zero of=5G bs=1G count=5`
   >
   > 
   >
   > 报错信息显示 **memory exhausted** ，内存不够
   >
   > dd命令中，bs（buffer size）是指每次读取内存的空间，count是指读取内存的次数
   >
   > 执行命令
   >
   > `free -h` 查询 memory的剩余空间，设置 bs 参数小于 free mem![1557280143011](C:\Users\Jarvis.LAPTOP-HV4II8QE\AppData\Roaming\Typora\typora-user-images\1557280143011.png)

2. ---

   **按照手册，上传大文件**

   docker命令无响应，systemctl status docker 显示 loaded，重启docker服务无响应

> 1. 查询docker进程号
>
>    `systemctl status docker`
>
> 2. 结束docker进程
>
>    `kill -9 [docker进程号]`
>
>    ​	[docker.service修改重启参数](<http://www.ruanyifeng.com/blog/2016/03/systemd-tutorial-part-two.html>)
>
>    ​	如果进程 **自动重启**
>
>    ​	编辑 /usr/lib/systemd/system/docker.service
>
>    ​	修改`Restart=on-failure` 为 `Restart=no`
>
>    ​	再次执行 kill 命令
>
> 3. 执行dockerd命令，设置docker开机启动
>
> ---

3. **按照手册，上传大文件**

   报错日志如下

   `2019/05/08 23:50:30  0187 das3.go:43 ▶ DEBU 298 Put bigfile/11449c9.20190508.235029.954 got The provided security credentials are not valid.`

   > 修改 tier/das3.go newV2改为newV4
   >
   > ---

2. **按照日志，上传大文件**

   迁移历史同名文件

   `./set.sh /root/mnt/1.txt migtate 10`

   报错

   `setfattr: /root/mnt/1.txt: No such file or directory`
   `setfattr: /root/mnt/1.txt: No such file or directory`

   > 之前 fast 路径下，有过1.txt
   >
   > 也对1.txt执行过set脚本
   >
   > 删除1.txt后，新建同名文件
   >
   > 再执行set脚本，报错如上
   >
   > **（待考证）**
   >
   > **需要删除fast目录下的 .inodes 隐藏文件**
   >
   > **在新代码中，删除文件是删除整个文件系统，不存在此问题**
   >
   > ---

3. **按照日志，上传大文件**

   tcpdump简介教程

   `tcpdump -i ens160 -s 0 -w PutObject.pcap`

   -i：指定网口

   -s：表示不截断报文

   -w：表示文件保存路径

   

   截取报文后，wireshark打开pcap文件，过滤器上输入过滤条件

   `tcp.port==8004`

   可以看到，8004端口的往来信息
   
   ---
   
6. fast目录下，删除某文件后，再创建同名文件，inode重复，无法上传新文件

   所有的文件操作都应该在mnt目录下执行

   创建，删除在mnt下执行才会全部改变（fast；.inode；mongo）